### ISSUE TITLE
Color System: Part II

### ISSUE THREAD

**Issue by Bonkles** [facebook/Rapid#1213]
### Description

Now that the #1187 is nearing completion, here are some next steps!

#1187 didn't add any new functionality- it just _prepared_ us to do cool things.  

Let's use this foundation to do something cool: add colorblindness modes. 

### Create a new color scheme for Red/Green Colorblindness

As per this [link](https://venngage.com/blog/color-blind-friendly-palette/), red/green colorblindness can be broken down into two categories- deuteranopia and tritanopia - and these account for the overwhelming majority of colorblindness experienced by people (north of 99%). 

Researching both an updated color scheme for just one of these would be a fine start. 

You'll need to augment the colors.json file with these new schemes, and the json will need to have each of these color schemes in a separate entry.  Name the current scheme something like 'default' and have the colorSystem load it, well, by default. :) 

### Make some UI controls
This improved color system isn't useful unless we plumb some controls up into user-land! 

We'll need a combobox control in the 'preferences' panel that shows all the different color schemes available.  

So the color system would need: 
- [ ] Another class method that returns the list of all available color schemes. This should use an `enum`. 
- [ ] A way to 'set' the current color scheme with one of those `enum` entries. 
- [ ] To signal the map to redraw whenever the color scheme is changed. 

The preferences panel [P] would need: 
- [ ] To call the API that gets the list of all available schemes
- [ ] To render a new section (in addition to the existing Privacy and Map Interaction sections) called 'Map Color Scheme', it should render a new combo box with all of the `enum` options provided by the color system
- [ ] To call the color system `setColorScheme()`

Here's what the preferences panel looks like right now: 
![image](https://github.com/facebook/Rapid/assets/1887955/d50673ad-acf6-47e9-886e-d7d55b976197)

**Comment by lauble** [comment]
**Task List**
So the color system would need:

- [x] Another class method that returns the list of all available color schemes. This should use an `enum`.
- [ ] A way to 'set' the current color scheme with one of those `enum` entries.
- [ ] To signal the map to redraw whenever the color scheme is changed.

The preferences panel [P] would need:

- [ ] To call the API that gets the list of all available schemes
- [ ] To render a new section (in addition to the existing Privacy and Map Interaction sections) called 'Map Color Scheme', it should render a new combo box with all of the enum options provided by the color system
- [ ] To call the color system `setColorScheme()`

**Comment by lauble** [comment]
PR reference #1230

**Comment by bhousel** [comment]
This was done!
