### ISSUE TITLE
Tracking issue - pull in changes from iD for v2.2.0

### ISSUE THREAD

**Issue by bhousel** [facebook/Rapid#1219]
This is just a placeholder issue for the work I'm pulling in from elsewhere.
We will include these fixes in the next Rapid release.

- [x] https://github.com/openstreetmap/iD/pull/10007
- [x] https://github.com/openstreetmap/iD/pull/10003
- [x] https://github.com/openstreetmap/iD/pull/9998
- [x] https://github.com/openstreetmap/iD/pull/9997
- [x] https://github.com/openstreetmap/iD/pull/9995
- [x] https://github.com/openstreetmap/iD/pull/9928
- [x] https://github.com/openstreetmap/iD/pull/9927
- [x] https://github.com/openstreetmap/iD/pull/9925
- [x] https://github.com/openstreetmap/iD/pull/9912
- [x] https://github.com/openstreetmap/iD/pull/9911
- [x] https://github.com/openstreetmap/iD/pull/9891
- [x] https://github.com/openstreetmap/id-tagging-schema/pull/985
- [x] https://github.com/openstreetmap/iD/pull/9817
- [x] https://github.com/openstreetmap/iD/pull/9692
- [x] https://github.com/openstreetmap/iD/pull/9685
- [x] https://github.com/openstreetmap/iD/pull/9667
- [x] https://github.com/openstreetmap/iD/pull/9650
- [x] https://github.com/openstreetmap/iD/pull/9633
- [x] https://github.com/openstreetmap/iD/pull/9630
- [x] https://github.com/openstreetmap/iD/pull/9424
- [x] https://github.com/openstreetmap/iD/issues/9422
