### ISSUE TITLE
Tracking issue - pull in changes from iD for v2.3.0

### ISSUE THREAD

**Issue by bhousel** [facebook/Rapid#1389]
This is just a placeholder issue for the work I'm pulling in from elsewhere.
We will include these fixes in the next Rapid release.

- [x] https://github.com/openstreetmap/iD/issues/7618, 
https://github.com/openstreetmap/iD/pull/10062
- [x] https://github.com/openstreetmap/iD/issues/5144 , 
https://github.com/openstreetmap/iD/pull/10066
- [x] https://github.com/openstreetmap/iD/pull/9501
- [x] https://github.com/openstreetmap/iD/issues/9502, 
https://github.com/openstreetmap/iD/issues/9788, 
https://github.com/openstreetmap/iD/pull/10089
- [x] https://github.com/openstreetmap/iD/pull/10000
- [x] https://github.com/openstreetmap/iD/issues/10065, 
https://github.com/openstreetmap/iD/pull/10165
- [x] https://github.com/openstreetmap/iD/pull/10121
- [x] https://github.com/openstreetmap/iD/pull/10123
- [x] https://github.com/openstreetmap/iD/pull/10127, 
https://github.com/openstreetmap/iD/pull/10144
- [x] https://github.com/openstreetmap/iD/issues/10135 , 
https://github.com/openstreetmap/iD/pull/10141
- [x] https://github.com/openstreetmap/iD/pull/10215
- [x] https://github.com/openstreetmap/id-tagging-schema/issues/1114
