### ISSUE TITLE
Tracking issue - pull in changes from iD for v2.4.0

### ISSUE THREAD

**Issue by bhousel** [facebook/Rapid#1494]
This is just a placeholder issue for the work I'm pulling in from elsewhere.
We will include these fixes in the next Rapid release.

- [x] https://github.com/openstreetmap/iD/issues/10332
https://github.com/openstreetmap/iD/pull/10291
- [x] https://github.com/openstreetmap/iD/pull/10278
https://github.com/openstreetmap/id-tagging-schema/issues/1263
- [x] https://github.com/openstreetmap/iD/pull/10333
https://github.com/openstreetmap/iD/issues/10323
- [x]  https://github.com/openstreetmap/iD/pull/10283
