### ISSUE TITLE
Tracking issue - pull in changes from iD for v2.5.0

### ISSUE THREAD

**Issue by bhousel** [facebook/Rapid#1626]
This is just a placeholder issue for the work I'm pulling in from elsewhere.
We will include these fixes in the next Rapid release.

- [x] https://github.com/openstreetmap/iD/pull/10554
- [x] https://github.com/openstreetmap/iD/issues/10522
https://github.com/openstreetmap/iD/pull/10523 
- [x] https://github.com/openstreetmap/iD/issues/9013 
https://github.com/openstreetmap/iD/issues/5634
- [x] https://github.com/openstreetmap/iD/issues/10573
https://github.com/openstreetmap/iD/pull/10581
- [x] https://github.com/openstreetmap/iD/pull/10459
