### ISSUE TITLE
Tracking issue - pull in changes from upstream for v1.1.8

### ISSUE THREAD

**Issue by bhousel** [facebook/Rapid#373]
This is just a placeholder issue for the work I'm pulling in from the upstream iD repo.
We're caught up to develop branch head and will include these fixes in the next RapiD release.

- [x] https://github.com/openstreetmap/iD/pull/8768
- [x] https://github.com/openstreetmap/iD/pull/8761
- [x] https://github.com/openstreetmap/iD/pull/8741
- [x] https://github.com/openstreetmap/iD/pull/8727
- [x] https://github.com/openstreetmap/iD/pull/8708
- [x] https://github.com/openstreetmap/iD/pull/8707
- [x] https://github.com/openstreetmap/iD/pull/8701
- [x] https://github.com/openstreetmap/iD/pull/8689
- [x] https://github.com/openstreetmap/iD/pull/8685
- [x] https://github.com/openstreetmap/iD/pull/8675
- [x] https://github.com/openstreetmap/iD/pull/8288

**Comment by bhousel** [comment]
FYI This release candidate is available for testing here (I apologize that the version number is not set correctly to v1.1.8):
https://mapwith.ai/rapid-test
Thanks @Bonkles for setting it up!
